### ISSUE TITLE
.jar

### ISSUE THREAD

**Issue by RandomPotato26** [caprica/picam#1]
to make it easier for me and anyone wanting to use this, making this a .jar file would be incredibly nice.

**Comment by caprica** [comment]
This project is currently in a pre-alpha state intended for experienced developers rather than general use - it is currently far from any formal release (mainly because of the show-stopper native hang mentioned in the project readme), so that's why currently there is no pre-built jar provided.

Doing a "git clone" and a "mvn install", whilst a bit more inconvenient than getting a pre-built jar file, is hardly difficult for an experienced developer.
